%YAML 1.2
---
name: 'testname'                  # ideally no spaces
gpu: 0                                 # gpu id to process on

training:
    precision: 'half'
    batch_size: 1024
    num_batch_splits: 1
    test_steps: 100
    num_test_evals: 10
    train_avg_report_steps: 10
    total_steps: 10000 
    checkpoint_steps: 1000
    shuffle_size: 2048
    lr_values:
        - 0.00001
        - 0
    lr_boundaries:
        - 11100
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    reg_loss_weight: 1.0
    moves_left_loss_weight: 0.1
    moves_left_gradient_flow: 1.0
    memory_limit: 9000
    sampling: "probabilistic"
    sampling_options:
        fraction: 32
model:
  filters: 128
  residual_blocks: 10
  se_ratio: 4
  value_channels: 32
  moves_left: 'v1'
  board_stack_size: 8
...
